# Generated by Django 3.2.6 on 2021-09-18 11:14

from django.db import migrations, models
import siteApp.models.offer_models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pay_method',
            field=models.ForeignKey(null=True, on_delete=models.SET(siteApp.models.offer_models.get_default_pay_method), to='siteApp.paymethod'),
        ),
    ]
