# Generated by Django 3.2.7 on 2021-09-02 16:54

from django.db import migrations
import siteApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', siteApp.models.UserManager()),
            ],
        ),
    ]
