# Generated by Django 3.2.7 on 2021-09-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_auto_20210918_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='eductationtype',
            name='once',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteApp.eductationtype'),
        ),
        migrations.AlterField(
            model_name='eductationtype',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='codename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='institution_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
