# Generated by Django 3.2.6 on 2021-09-23 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_auto_20210922_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='_siteApp_user_collaborators_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
