# Generated by Django 3.2.7 on 2021-09-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siteApp.models.user_models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0005_alter_user_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_modified_on',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='finalized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='private',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articleaddon',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siteApp.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=siteApp.models.user_models.upload_profile_picture),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.PositiveBigIntegerField()),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
