# Generated by Django 3.2.7 on 2021-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0007_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_articles',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='num_comments',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
