# Generated by Django 3.2.7 on 2021-09-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0008_auto_20210929_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='num_articles',
            new_name='num_likes',
        ),
    ]
