# Generated by Django 3.2.7 on 2021-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0009_rename_num_articles_article_num_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='num_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
